### ISSUE TITLE
Exception when parsing math extension's images

### ISSUE THREAD

**Issue by joakin** [joakin/loot#43]
Visit http://localhost:7001/slim/Euclidean_algorithm for an example.

One of the exceptions:

```
<img class="mwe-math-fallback-image-inline tex" alt="\omega ={\frac {1+{\sqrt {D}}}{2}}." src="//upload.wikimedia.org/math/0/3/a/03ae3c405c8c520d587a73b24e4b1b33.png" typeof="mw:Extension/math" data-mw='{"name":"math","attrs":{},"body":{"extsrc":" \\omega = \\frac{1 + \\sqrt{D}}{2}. "}}' about="#mwt732" id="mwCbA">
 TypeError: Cannot read property 'value' of null
    at imagify (/Users/jhernandez/dev/loot/lib/transforms/common/index.js:93:38)
    at Object.exports.slim (/Users/jhernandez/dev/loot/lib/transforms/common/index.js:7:3)
    at module.exports (/Users/jhernandez/dev/loot/lib/transforms/slim.js:3:48)
    at /Users/jhernandez/dev/loot/lib/routes/restbase-req-handler.js:31:33
    at ConcatStream.<anonymous> (/Users/jhernandez/dev/loot/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/Users/jhernandez/dev/loot/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:509:14)
    at endWritable (/Users/jhernandez/dev/loot/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:519:3)
    at ConcatStream.Writable.end (/Users/jhernandez/dev/loot/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:484:5)
```

**Comment by joakin** [comment]
Seems to be related to that image tag not having the width and height attributes (https://github.com/joakin/loot/blob/master/lib/transforms/common/index.js#L93-L94)

Solution would be not adding width and height to the inline style wrapper if the tag didn't have them.
